stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:                         # with params
    - data_ingestion.test_size      # with params
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    params:                             # with params
    - feature_engineering.max_features  # with params
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:                           # with params
    - model_building.n_estimators     # with params
    - model_building.random_state     # with params
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
#params:
#- dvclive/params.yaml
#metrics:
#- dvclive/metrics.json
#plots:
#- dvclive/plots/metrics:
#    x: step